// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0FORpWthMWhKDyIUgQ9oSc6pOHvMMJeU',
    appId: '1:306451984630:web:10978ae223ace93f72fcd7',
    messagingSenderId: '306451984630',
    projectId: 'baroni-2025',
    authDomain: 'baroni-2025.firebaseapp.com',
    storageBucket: 'baroni-2025.firebasestorage.app',
    measurementId: 'G-8364ZCM9CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwTIQcq4_2nETEpiJ9-SK9zBrcMuyzOo8',
    appId: '1:306451984630:android:ae79e6554b2a55a172fcd7',
    messagingSenderId: '306451984630',
    projectId: 'baroni-2025',
    storageBucket: 'baroni-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAQyWX4MlNj71h1lLAJ2cf4LnrxQww-U4',
    appId: '1:306451984630:ios:3476a1205094343172fcd7',
    messagingSenderId: '306451984630',
    projectId: 'baroni-2025',
    storageBucket: 'baroni-2025.firebasestorage.app',
    iosClientId: '306451984630-kpheg1mh8o3qji2mnhs152ri5a3kgl67.apps.googleusercontent.com',
    iosBundleId: 'com.baroni.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAQyWX4MlNj71h1lLAJ2cf4LnrxQww-U4',
    appId: '1:306451984630:ios:80f4ddafcd1ecd5672fcd7',
    messagingSenderId: '306451984630',
    projectId: 'baroni-2025',
    storageBucket: 'baroni-2025.firebasestorage.app',
    iosClientId: '306451984630-7stkvf5e1t6a0eog99m7j8ev1mtigglm.apps.googleusercontent.com',
    iosBundleId: 'com.example.baroniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0FORpWthMWhKDyIUgQ9oSc6pOHvMMJeU',
    appId: '1:306451984630:web:c213ba09e177f31872fcd7',
    messagingSenderId: '306451984630',
    projectId: 'baroni-2025',
    authDomain: 'baroni-2025.firebaseapp.com',
    storageBucket: 'baroni-2025.firebasestorage.app',
    measurementId: 'G-C4CG34R3DN',
  );
}
